#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 16 09:14:21 2020

@author: hofmann
"""


         
get_a = lambda k,m,n: k*(m**2-n**2)
get_b = lambda k,m,n: 2*k*m*n
get_c = lambda k,m,n: k*(m**2+n**2)
for k in range(1,10):
    for m in range(1,10):
        for n in range(1,m):
            a = get_a(k,m,n)
            b = get_b(k,m,n)
            c = get_c(k,m,n)
            if gcd(m,n)==1:
                print("a,b,c:",a,b,c)
                
